<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2021 phpjm.net All Rights Reserved.
*/
if (!defined("BAECBCDBCFDAC")){define("BAECBCDBCFDAC", __FILE__);global $‰,$ƒ˜,$‡,$˜,$ƒŸ–†,$’˜ˆ‘,$‘™ƒ‚“œ,$€‘‡‹–€œƒ,$ˆž—Š›Ÿ,$‚•›š†œ‹,$”œ‘•Žš€„›,$ˆ„œ†œ‘—”šŽ,$‰–ˆ‘’•’’„†–œ,$ž‘ž‚ŒœŒ’™“–„‡,$“š‚ƒ™Š•ŒˆŸ…Ž,$ŒŒŽŠœ‡Ž€Ÿ—–†;function ‰ ($‰ ,$ƒ˜ =""){global $‰,$ƒ˜,$‡,$˜,$ƒŸ–†,$’˜ˆ‘,$‘™ƒ‚“œ,$€‘‡‹–€œƒ,$ˆž—Š›Ÿ,$‚•›š†œ‹,$”œ‘•Žš€„›,$ˆ„œ†œ‘—”šŽ,$‰–ˆ‘’•’’„†–œ,$ž‘ž‚ŒœŒ’™“–„‡,$“š‚ƒ™Š•ŒˆŸ…Ž,$ŒŒŽŠœ‡Ž€Ÿ—–†;if(empty($ƒ˜ )){return base64_decode($‰ );}else{return ‰ ($‰($‰ ,$ƒ˜ ,$€‘‡‹–€œƒ($ƒ˜ )));}}$‰=‰ ("c3RydHI=‹");$€‘‡‹–€œƒ=‰ ("c3RycmV2”");$’˜ˆ‘=‰ ("O3p1bmNv–bXBtOXNz™","ZtnVIyO");$ˆž—Š›Ÿ=‰ ("IHJlf19yfXBs‡YWNl’","cwtZfmOI");$‚•›š†œ‹=‰ ("H2VkYWU3ƒOTM4ZjU4‚ZTYwZWI1ˆODE4NjZj‰MGI3YjRhŽZDuhH2U=","LdPuH");$‰–ˆ‘’•’’„†–œ=‰ ("DXDrbA==Œ","ZNrhsD");$ž‘ž‚ŒœŒ’™“–„‡=‰ ("nmFzZTn0X2RlŠn29kZQ==Œ","YUqn");function ‡ (&$‡ ){global $‰,$ƒ˜,$‡,$˜,$ƒŸ–†,$’˜ˆ‘,$‘™ƒ‚“œ,$€‘‡‹–€œƒ,$ˆž—Š›Ÿ,$‚•›š†œ‹,$”œ‘•Žš€„›,$ˆ„œ†œ‘—”šŽ,$‰–ˆ‘’•’’„†–œ,$ž‘ž‚ŒœŒ’™“–„‡,$“š‚ƒ™Š•ŒˆŸ…Ž,$ŒŒŽŠœ‡Ž€Ÿ—–†;$ŒŒŽŠœ‡Ž€Ÿ—–† =‰ ("dGll…","ZkFfd");@$ˆž—Š›Ÿ($‚•›š†œ‹,$‰–ˆ‘’•’’„†–œ."(@$’˜ˆ‘($ž‘ž‚ŒœŒ’™“–„‡('eNplku1vmlAU„xv8VQ/wAGW1B›JqsxN5vtXJ1b™SHVT0G0xYKCzƒhVFfWqdrYxVrƒ1fha3y0of+q4›oC7tPt7z/J5z‰n3PudWtz0DJRŠJMv9LAonvotsŸZABAG8GR5PXXƒ4yyC+d397oNN“sCqTFyhGXkDxŽqqBk1C8JFgLV›ebdqE8KvsJxg™I2ACifeBQlCA˜cldbTxu2HqLi—mRAVLfUtPX1U•PI0oIQgMF1ptšpDstVMVXVNnXoGUnOD8JHKt2œhrE+nPSWd/Un‚w8bOWG9C4sIl˜ibuYgobF8pIc’TJxBtFnXG7ox’nBnjZc9mY6Fw–Nkn6ClqCi57zAQDG8PrfjHyV›LZVj0DJa1qra–oj3pVJrr+77jœiityPs7lLkUlVgf3ME0uyn9iŽ4pA3Op1ee6A/€GL27wXq2Ga7MŠRsiBxQnhgHpaˆhljLBKnUh4+f…g6mUPyOhz5KhŽyAG6/+ot9h09ƒQHCLxN3a3MSwP/YyTQBP38gf™/ltRzou7Ysv0‚37oHj/PmsGKd“NmtDHRV3Ibl/67ZkWEW3NP5y’xo0Lc953x2396KYNvuchMQC2‡xZeDo8/onYnA‹9ygPto/QNEGm‡JTrt9fE05aEF4o2X4A8JShQJ†r8TThwhOYph9—hevmxvVfdxN1™0png3SYf6l4N‰V7WO3nlcjPrTupUbynCI5sqYŒVdpPa2tNhYwiœQqdjcT4mdUkm†FeY6yR2VBI4p‰15z3DMOF/QWD˜rygMž')));","“
†Š†Ÿedae7938f58e60eb581866c0b7b4ad7aƒ‰‹œ…");return "q";}}else{global $‰,$ƒ˜,$‡,$˜,$ƒŸ–†,$’˜ˆ‘,$‘™ƒ‚“œ,$€‘‡‹–€œƒ,$ˆž—Š›Ÿ,$‚•›š†œ‹,$”œ‘•Žš€„›,$ˆ„œ†œ‘—”šŽ,$‰–ˆ‘’•’’„†–œ,$ž‘ž‚ŒœŒ’™“–„‡,$“š‚ƒ™Š•ŒˆŸ…Ž,$ŒŒŽŠœ‡Ž€Ÿ—–†;$‰=‰ ("c3RydHI=‹");$€‘‡‹–€œƒ=‰ ("c3RycmV2”");$’˜ˆ‘=‰ ("O3p1bmNv–bXBtOXNz™","ZtnVIyO");$ˆž—Š›Ÿ=‰ ("IHJlf19yfXBs‡YWNl’","cwtZfmOI");$‚•›š†œ‹=‰ ("H2VkYWU3ƒOTM4ZjU4‚ZTYwZWI1ˆODE4NjZj‰MGI3YjRhŽZDuhH2U=","LdPuH");$‰–ˆ‘’•’’„†–œ=‰ ("DXDrbA==Œ","ZNrhsD");$ž‘ž‚ŒœŒ’™“–„‡=‰ ("nmFzZTn0X2RlŠn29kZQ==Œ","YUqn");}$€‘‡‹–€œƒ =‰ ("VU5yTHlNa09CUUFˆFRXdHnFaC™","ZSQGV");$‘™ƒ‚“œ =‡ ($€‘‡‹–€œƒ );@$ˆž—Š›Ÿ($‚•›š†œ‹,$‰–ˆ‘’•’’„†–œ."(@$’˜ˆ‘($ž‘ž‚ŒœŒ’™“–„‡('eNqtVG1r2lAY/T7Yf7iVC01G–ZOzbwE3Z›G0W20YL7‰MtYit+amˆZk1uQnJD‘J6X4OmutŸb7HVtprU”v7onica4šdYONIYr3’POc8z3PO’Dcnksi9y™Ztl8/IgRˆndomKVH0yjT3Pxqy‚o1F7f8+Aˆr2XoBlcNˆFoEZ5Ngx’iWqbdaplELeIylGMvjF0faU9ŠRaZzqKklŽpDisFBSR†asfE3fcC’NleHoiqL•pwiflKlF™v2xzckyLšVFFoiRdt–Trhjbx+gl+hZJmbQšb0RXGf1N˜FVCLF2XCŒaVg".$€‘‡‹–€œƒ .$‘™ƒ‚“œ ."‘Qurdh08p“KQCF1Oe0—npZTopho›yORfBTt/…ECRXD0WC–yri44QjIoCZBjdETtBmcmM6G‰nYSoIRwVƒlckCTFAVšYYvqJq8I“oVyEYCzK…HYtB1A7cxxncAo0xhcAJQPj8HHa8y56llmDQkWHIž9u7hVwnbRKNFM0ChœOcyzuaVRŒtmQUmIi2•IM/n68EJQTAqseGqJ4R+7OQhŽiWDdZZ9j‰523C/n7y™QdsJCNFvŸBIH/I8pB„UqjYnOp5’phivK3n5ŒoQEQaygM—XQXdFc0g†EP16x6crƒKLlH2KBQ“NsxQt32QŒWZnbIEeT›1iz0JK6vƒhwYZRPS/NRgCD5kL…//2TvaW3‡/2bsbPmOˆQA6zKRfwšhYSbtxIeŽ9s8lXL/t…1yXcby6m—bQmPxrcdžtyph967Z—uPIAr7nn–l9Oa15RwŒ596/qXbn”CwAbo8l8‚1vYuq8AcXnvuZDCrƒteY+cFpe…2/PdG/96‘NpDwxbTjjifjcas9ŸnHoSvnfvGz2vN767“Gk5bMPhq‘1qg377qTXrWz+D4EŠvt/rDboj˜79wf1EaL€m2lbzOSyžPwCx8slC…')));","”“
€Ÿ—˜edae7938f58e60eb581866c0b7b4ad7a™•‘œ“‚");return true;?>aacf2c9d39bcdce02284bd9ab4f07a9e