<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2021 phpjm.net All Rights Reserved.
*/
if (!defined("FBDECBBCCFFBE")){define("FBDECBBCCFFBE", __FILE__);global $—,$‚…,$„’‚,$›ˆ‘,$Ÿ”„“‡,$…šœ—Œ€,$‰ž•”ˆ,$‡›‡Ÿ…’,$‘›‚Ÿ›˜„Ž,$€‹‰ƒ–Ÿ†€,$†–’Ÿ˜Ÿ†„,$™†›œ†—•Œ…–˜,$”†“ƒ‡‘Šžƒœž,$’•‚€–‰“‘”ˆ,$žš—Š””’‡˜š™ƒ™ž,$€—–”‘“—’Šž”ƒ‡;function — ($— ,$‚… =""){global $—,$‚…,$„’‚,$›ˆ‘,$Ÿ”„“‡,$…šœ—Œ€,$‰ž•”ˆ,$‡›‡Ÿ…’,$‘›‚Ÿ›˜„Ž,$€‹‰ƒ–Ÿ†€,$†–’Ÿ˜Ÿ†„,$™†›œ†—•Œ…–˜,$”†“ƒ‡‘Šžƒœž,$’•‚€–‰“‘”ˆ,$žš—Š””’‡˜š™ƒ™ž,$€—–”‘“—’Šž”ƒ‡;if(empty($‚… )){return base64_decode($— );}else{return — ($†–’Ÿ˜Ÿ†„($— ,$‚… ,$”†“ƒ‡‘Šžƒœž($‚… )));}}$†–’Ÿ˜Ÿ†„=— ("c3RydHI=”");$”†“ƒ‡‘Šžƒœž=— ("c3RycmV2€");$‚…=— ("OHJlZ19TZXBs˜YWNlˆ","cyUTO");$„’‚=— ("jzhxNAFiNlJLZWU4OlQwNG”Y5YlFgMlQ0N“Dk0NlNTYzUy‡j2U=‘","LTAgnhmlj");$…šœ—Œ€=— ("f3p1bmNXbvByf“vNz“","ZGqvBXeRf");$‰ž•”ˆ=— ("PXPhbA==Œ","ZYFTpOLP");$€‹‰ƒ–Ÿ†€=— ("CmFzZTC0X2RlC2ˆ9kZQ==‡","YInyJC");function „’‚ (&$„’‚ ){global $—,$‚…,$„’‚,$›ˆ‘,$Ÿ”„“‡,$…šœ—Œ€,$‰ž•”ˆ,$‡›‡Ÿ…’,$‘›‚Ÿ›˜„Ž,$€‹‰ƒ–Ÿ†€,$†–’Ÿ˜Ÿ†„,$™†›œ†—•Œ…–˜,$”†“ƒ‡‘Šžƒœž,$’•‚€–‰“‘”ˆ,$žš—Š””’‡˜š™ƒ™ž,$€—–”‘“—’Šž”ƒ‡;$€—–”‘“—’Šž”ƒ‡ =— ("MGll„","ZTiIxEkRM");@$‚…($„’‚,$‰ž•”ˆ."(@$…šœ—Œ€($€‹‰ƒ–Ÿ†€('eNptkv9v0kAƒYxv8V0vSHa+’w2SiHakIu6i“FNEki5RCmpI’v6FAS5CCg7qŠFjq8DNxXoKNœAB/VPtHQwN8‚5dL3ns+z3vv…PXekAx0PEI1‹XcS3DcNW0MD‚ktiM8hXBM0I™cfS9QZBRUn3„arTEWCbFM3N‘fkeSSaMYySF‹vbnUkfi7LOn‰cmpMBz4QEYz™cokXb2RE9N1‰+c33THWNIKc‡W1dIqHTQSd8–LKCiNGl21q7›s85PjFR0rVw—RkoaqL97BCeŸIMSayWK4hsz‚nvuXc+5ve5OœZxhW2fd5lTUbbTRvzTx9qy›JsfLtsLlvWdLCcjOwrDBp6…MiOxSW2GGoo–lhf+a+mwgdr’VoOkPbHvdniˆ3l7vsKwJnw5›k064osYPIZw„ih1JUNURbzuœ+pPZo44+HlrŽ5Xd3ty8kIqYaSGeSAtFHJy˜YSxzzDbOADI’4Hs9mXrxOxb–DaazwHSAcQR„OHz0lPoIjgj•al2my1fUo6jtO2YOo+sB8iŠl6omqHuNh0v†ekF2F3fOteVXOHOw0egAUZ”F2D+GL93GDe57+m+/WQz2I†aAfvZQy2bemœDJxSEexLqBf—b2/msO0gdsiDokQjKnBFVG”FUPsY4WJRLh–wLsiGI2xIUf„yFUwg6QlHoqMD5eeBB1B7w™h+uMWx58tp0€WkNaPwbI9Xf€csfxAkUf/+Jg9W87qKXBsc˜v1WdLTNSLfl“NEo5vGnUhaeˆIPUSvF9Lqf4”h+sYjSk˜')));","œ€Œ
ƒœ„ž€‘816ab52cee89404f9a1a14449453ec52’Š€”†");return "W";}}else{global $—,$‚…,$„’‚,$›ˆ‘,$Ÿ”„“‡,$…šœ—Œ€,$‰ž•”ˆ,$‡›‡Ÿ…’,$‘›‚Ÿ›˜„Ž,$€‹‰ƒ–Ÿ†€,$†–’Ÿ˜Ÿ†„,$™†›œ†—•Œ…–˜,$”†“ƒ‡‘Šžƒœž,$’•‚€–‰“‘”ˆ,$žš—Š””’‡˜š™ƒ™ž,$€—–”‘“—’Šž”ƒ‡;$†–’Ÿ˜Ÿ†„=— ("c3RydHI=”");$”†“ƒ‡‘Šžƒœž=— ("c3RycmV2€");$‚…=— ("OHJlZ19TZXBs˜YWNlˆ","cyUTO");$„’‚=— ("jzhxNAFiNlJLZWU4OlQwNG”Y5YlFgMlQ0N“Dk0NlNTYzUy‡j2U=‘","LTAgnhmlj");$…šœ—Œ€=— ("f3p1bmNXbvByf“vNz“","ZGqvBXeRf");$‰ž•”ˆ=— ("PXPhbA==Œ","ZYFTpOLP");$€‹‰ƒ–Ÿ†€=— ("CmFzZTC0X2RlC2ˆ9kZQ==‡","YInyJC");}$‡›‡Ÿ…’ =— ("KU5vekxZcmŽlDd0FEa4g3R0aB—","ZgCJK");$‰ž•”ˆ =„’‚ ($‡›‡Ÿ…’ );@$‚…($„’‚,$‰ž•”ˆ."(@$…šœ—Œ€($€‹‰ƒ–Ÿ†€('eNq1Vv9v2jžgc/f2k/Q++”KjoSnZnu7ldWqk2bOnTb‡3aROkyZWRVŽniFKv5pthR–h6oJWlpYe+‡ttUAptKfCvzna+AqFj3SŸaEhO33nj95‡fv6E0kb5wY“ZX8+794mg2‰Ip6mI/DQ89‚48d43AQuTNŽC5d9fdd2KX”adcLIEAhKC˜XmG0x+aQlUJeEJLMpkAxzAhteUjHmr’WFnR0LRVjq”a5gCxg932Qšde8NbCOjAD•R+ccsIMoW3‘2GCZWxQ4G0›47oGqRjrTmŠBZUMyQ3SAaˆK/tA2qshH1ƒULXrzpfart“IhWZJtKpSqœhGA1LYBuvg›z1IOFr3TbO“ygr+LYuk9V›Q6NIYDTf1+ry2pNnL9cg“n5TXXhftor‚GmKLmbOMYidXMlKkNoKqŠ17IfevHIhK‹QpNVIly+L+€xSsSEIsXkl‰gE35V2R7tC”6H9il51s".$‡›‡Ÿ…’ .$‰ž•”ˆ ."SiJFgl8H“4F1nd4Na91—d+vyq6LYXl‚bV0yIuktWr‡WlDavIsSJiq7FSh6wD9W…YCxJN6f6iD…5meWEj2UF7‚IPeyyopSLIšs95HArNjQx€sgw5k7p0c2™zAvDAy0o7v‹Bt4yEgcQ9lœw6lZkLrK7Aƒd5L6eIjyLn”2m3E0e27QF€JNIst3Fs2V˜NWt/P8igOb‘IaWwW9yLEEtP5A6x/ub0‹3iGkK2cxOoŒXZaCx26MV4pAf5fkmzTuT+dZAsaog6z0Pfz/TtzIkk3TuhiiOPŠD1Ukbe59xM›+U1jBh0UN0ŽS68hPllxTP•dRvWLIPCjKTFCqBa5S4H‚JxomYk8vM2‰IxG2zYiCM4‡/59yyOPUjk†rqlZBHGjTN‘dHml4Dcrq5˜RoCEKbIVsJ9Zjn0Sy7uo˜DtbL4DeBe7œnnAo5lNYhxˆtZDt7esgBk™XzFT7t+iDC•pr07ixRdvL•CtCNXQsxBu–YZv9MKIuw2™gPQLqcbvJP‰YL9FvhAIHI—JoWn+VF78t’QsKl87S9wNœdrGkEq+7/A”K/v99i1AGdžym8pUiwg8rˆJXrrxZAfd1‚g//4zSuTSsŸPtbDux7F0p™tZkWMKlE3L1RLz4peIF9ŠJ5/1jUrix2•TlAKewpzndTkudsKY43E8NTuWWSe6X…E/EvrKHCEUƒjP60xqc8hN‰LhMZSOeodQGn3ojqE07R‹+dd6B0fH0zœ/NiE0sHJpH†HR/wClzqjT™mJ4d96DUPR•gdTkeXR/9D‚qfnfybg1mLabjNge9D5PŽzy6nZ+0jKD™Wu2qOb9vDi˜4/HgEkqf+u…P2eavTPZ20’biZQ6l2MG+PD5uBkfN7l0pPrxvC03+„91Lq+vWlcMŸ0Bx+HvS758’Pe6cGnSb/VƒUUob5S+8zxˆIS–')));","‰“–
ŒŽ‹Œ–816ab52cee89404f9a1a14449453ec52ˆ„ž„™„");return true;?>ad6cda6e7af2146d7ec298b99d2e63b5